version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run test
          command: |
            npm run testlocal
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage
workflows:
  build_test:
    jobs:
      - run_tests